# Generated by Django 5.0.4 on 2024-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="plot",
        ),
        migrations.AddField(
            model_name="movie",
            name="searchCount",
            field=models.IntegerField(default=0),
        ),
    ]
