# Generated by Django 5.0.4 on 2024-08-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_remove_movie_plot_movie_searchcount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
    ]
