# Generated by Django 5.0.4 on 2024-08-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_remove_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(default="gen", max_length=250),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
