# Generated by Django 5.0.4 on 2024-08-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0004_movie_genre_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdbrating",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="movie",
            name="rated",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
