# Generated by Django 5.0.4 on 2024-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_movie_imdbrating_movie_rated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(default="Unknown", max_length=10),
        ),
    ]
